// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MyCourse.Models.Services.Infrastructure;

namespace MyCourse.Migrations;

[DbContext(typeof(MyCourseDbContext))]
[Migration("20210927072440_TriggerCourseRating")]
partial class TriggerCourseRating
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        #pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.1");

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClaimType")
                    .HasColumnType("TEXT");

                b.Property<string>("ClaimValue")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderKey")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("TEXT");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("RoleId")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<string>("LoginProvider")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .HasColumnType("TEXT");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("INTEGER");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<string>("FullName")
                    .HasColumnType("TEXT");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("PasswordHash")
                    .HasColumnType("TEXT");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("TEXT");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("INTEGER");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("TEXT");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Course", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Author")
                    .HasColumnType("TEXT");

                b.Property<string>("AuthorId")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("ImagePath")
                    .HasColumnType("TEXT");

                b.Property<double>("Rating")
                    .HasColumnType("REAL");

                b.Property<string>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AuthorId");

                b.HasIndex("Title")
                    .IsUnique();

                b.ToTable("Courses");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Lesson", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("CourseId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("TEXT");

                b.Property<int>("Order")
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(1000);

                b.Property<string>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CourseId");

                b.ToTable("Lessons");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Subscription", b =>
            {
                b.Property<int>("CourseId")
                    .HasColumnType("INTEGER");

                b.Property<string>("UserId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("PaymentDate")
                    .HasColumnType("TEXT");

                b.Property<string>("PaymentType")
                    .HasColumnType("TEXT");

                b.Property<string>("TransactionId")
                    .HasColumnType("TEXT");

                b.Property<int?>("Vote")
                    .HasColumnType("INTEGER");

                b.HasKey("CourseId", "UserId");

                b.HasIndex("UserId");

                b.ToTable("Subscriptions");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("MyCourse.Models.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("MyCourse.Models.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MyCourse.Models.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("MyCourse.Models.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Course", b =>
            {
                b.HasOne("MyCourse.Models.Entities.ApplicationUser", "AuthorUser")
                    .WithMany("AuthoredCourses")
                    .HasForeignKey("AuthorId");

                b.OwnsOne("MyCourse.Models.ValueObjects.Money", "CurrentPrice", b1 =>
                    {
                        b1.Property<int>("CourseId")
                            .HasColumnType("INTEGER");

                        b1.Property<float>("Amount")
                            .HasColumnType("REAL")
                            .HasColumnName("CurrentPrice_Amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("TEXT")
                            .HasColumnName("CurrentPrice_Currency");

                        b1.HasKey("CourseId");

                        b1.ToTable("Courses");

                        b1.WithOwner()
                            .HasForeignKey("CourseId");
                    });

                b.OwnsOne("MyCourse.Models.ValueObjects.Money", "FullPrice", b1 =>
                    {
                        b1.Property<int>("CourseId")
                            .HasColumnType("INTEGER");

                        b1.Property<float>("Amount")
                            .HasColumnType("REAL");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.HasKey("CourseId");

                        b1.ToTable("Courses");

                        b1.WithOwner()
                            .HasForeignKey("CourseId");
                    });

                b.Navigation("AuthorUser");

                b.Navigation("CurrentPrice");

                b.Navigation("FullPrice");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Lesson", b =>
            {
                b.HasOne("MyCourse.Models.Entities.Course", "Course")
                    .WithMany("Lessons")
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Course");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Subscription", b =>
            {
                b.HasOne("MyCourse.Models.Entities.Course", "Course")
                    .WithMany()
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MyCourse.Models.Entities.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.OwnsOne("MyCourse.Models.ValueObjects.Money", "Paid", b1 =>
                    {
                        b1.Property<int>("SubscriptionCourseId")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("SubscriptionUserId")
                            .HasColumnType("TEXT");

                        b1.Property<float>("Amount")
                            .HasColumnType("REAL");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.HasKey("SubscriptionCourseId", "SubscriptionUserId");

                        b1.ToTable("Subscriptions");

                        b1.WithOwner()
                            .HasForeignKey("SubscriptionCourseId", "SubscriptionUserId");
                    });

                b.Navigation("Course");

                b.Navigation("Paid");

                b.Navigation("User");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.ApplicationUser", b =>
            {
                b.Navigation("AuthoredCourses");
            });

        modelBuilder.Entity("MyCourse.Models.Entities.Course", b =>
            {
                b.Navigation("Lessons");
            });
#pragma warning restore 612, 618
    }
}
